### ISSUE TITLE
No bower repository

### ISSUE THREAD

**Issue by rollecode** [magnetikonline/sassboilerplate#1]
Can you add bower repository for these? Thanks!

**Comment by magnetikonline** [comment]
Leave it with me :)

**Comment by magnetikonline** [comment]
I think I'll close this out - but I might get around oneday to npm this (as per your other issue request) - but dunno, just _feels_ wrong to put CSS/frontend things like this onto npm... ?

**Comment by rollecode** [comment]
Bower no longer necessary for me, but npm is. Why does it feel wrong? It feels more wrong not to have version control or upstream updates in projects. It's pretty normal to have front end stuff on npm nowadays. Please reconsider it. At least I want to know why not.

**Comment by d2s** [comment]
Old article ([Why We Should Stop Using Bower - And How to Do It](https://gofore.com/stop-using-bower/)) from 2015 tells about npm basics, but most likely are more fresh guidelines on how to use it elsewhere.

Regarding npm as a distribution platform for CSS & Sass libraries, that is how large part of developers distribute their libraries these days. Clearly not a perfect way, but at least scalable.

**Comment by rollecode** [comment]
Yeah, I agree with you @d2s, stopped using bower years ago, after opening this issue. But clearly @magnetikonline is stating this should not be on npm either - I beg to disagree.

**Comment by magnetikonline** [comment]
@ronilaukkarinen it's cool! was just raising the question! 😄  I'll make it NPM, I promise!

Do you have an example of a "well done" NPM frontend/CSS example I can copy on npmjs.org?

(I'll take this over to the other issue ticket).

**Comment by d2s** [comment]
@magnetikonline Tachyons http://tachyons.io/ has individual style components in a various npm packages.

Sass version of it https://github.com/tachyons-css/tachyons-sass even has a build script for generating CSS output from the Sass files. Useful example, potentially.

**Comment by magnetikonline** [comment]
@d2s thank you sir! I'll re-paste your comments into the other issue.
