### ISSUE TITLE
Add as npm package

### ISSUE THREAD

**Issue by rollecode** [magnetikonline/sassboilerplate#2]
Could not find this with [npm](https://www.npmjs.com/search?q=sassboilerplate). Many have moved from bower to npm-only, so have I. It would be great to be able to use this directly from upstream. Would you be so kind to add sassboilerplate as npm package. Appreciated!

**Comment by magnetikonline** [comment]
Hey @ronilaukkarinen do you have an example of a "well done" NPM frontend/CSS example I can copy on npmjs.org?

Just so I craft the `package.json` to suit - since I only have authored "node/javascript" packages thus far 👍

**Comment by magnetikonline** [comment]
Notes (from @d2s).

```
Tachyons http://tachyons.io/ has individual style components in a various npm packages.

Sass version of it https://github.com/tachyons-css/tachyons-sass even has a build script for generating CSS output from the Sass files. Useful example, potentially.
```

**Comment by rollecode** [comment]
Other examples that are in npm:

- [jeet](https://github.com/mojotech/jeet)
- [luxbar](https://github.com/balzss/luxbar)
- [normalize.css](https://github.com/necolas/normalize.css/)

**Comment by d2s** [comment]
Another good example of a CSS styles distributed with `npm`:

- [BafS/Gutenberg: Modern framework to print the web correctly.](https://github.com/BafS/Gutenberg)
  - Sass source files + Gulp task to convert them to CSS format.
  - [`package.json`](https://github.com/BafS/Gutenberg/blob/master/package.json) that has the structure & keywords.

**Comment by magnetikonline** [comment]
Thx @ronilaukkarinen @d2s - I'll pull my :crossed_fingers: out and get this done!

Appreciate all your links here :+1:

**Comment by rollecode** [comment]
Awesome!

**Comment by magnetikonline** [comment]
And we're live! At 167495fb50ea446c44ffa4fe0431284909bb715d.

https://www.npmjs.com/package/sassboilerplate


Thanks @ronilaukkarinen & @d2s - appreciate the feedback!

**Comment by rollecode** [comment]
Thanks a lot! Finally can implement this directly from source.
